import {User} from './User';
import {Company} from './Company'
import { CustomMap } from './CustomMap';



//we have achieved restricting to googleMap through the customMap class. 
const company = new Company();
const user = new User();
// create an instance of the CustomMap and assign to a variable
const customMap = new CustomMap('map');
// access the addmarker method and pass in the user to create a marker on the map(remember that the lat and lng are randomly generated by lat and lng)
//behind the scenses typescript implicitly checking and inspecting the type of the object to see if it satisfies the interface in CustomMap
customMap.addMarker(user);
customMap.addMarker(company)


